swagger: "2.0"
info:
  description: "Transaction balance watch"
  title: "Balance Watch"
  version: "1.0.0"
basePath: "/watch"

paths:
  /transactionBoard/{year}/{month}:
    get:
      tags:
        - "transaction board"
      produces:
        - "application/json"
      parameters:
        - name: "year"
          in: "path"
          required: true
          type: "integer"
          format: "int32"
        - name: "month"
          in: "path"
          required: true
          type: "integer"
          minimum: 1
          maximum: 12
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Board"
        400:
          description: "Invalid year/month supplied"
        404:
          description: "Board not found"
definitions:
  Board:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      year:
        type: "integer"
        format: "int32"
      month:
        type: "integer"
        format: "int32"
      startAmt:
        type: "number"
        format: "currency"
      account:
        type: "string"
