swagger: "2.0"
info:
  description: "Transaction balance watch"
  title: "Balance Watch"
  version: "1.0.0"
basePath: "/watch"

paths:
  /transactionBoards/{year}/{month}/{account}:
    get:
      tags:
        - "transaction boards"
      produces:
        - "application/json"
      parameters:
        - name: "year"
          in: "path"
          required: true
          type: "integer"
          format: "int32"
        - name: "month"
          in: "path"
          required: true
          type: "integer"
          minimum: 1
          maximum: 12
        - name: "account"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Board"
        400:
          description: "Invalid year/month supplied"
        404:
          description: "Board not found"
  /transactionBoards:
    post:
      tags:
        - "transaction boards"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "board that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Board"
      responses:
        201:
          description: "Success"
          headers:
            X-Internal-Id:
              type: "integer"
              format: "int64"
              description: "Internal ID used by the database"
        405:
          description: "Invalid input"
    put:
      tags:
        - "transaction boards"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "board that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Board"
      responses:
        405:
          description: "Invalid input"

definitions:
  Board:
    type: "object"
    properties:
      year:
        type: "integer"
        format: "int32"
      month:
        type: "integer"
        format: "int32"
        minimum: 1
        maximum: 12
      startAmt:
        type: "number"
        format: "currency"
      account:
        type: "string"
