swagger: "2.0"
info:
  description: "Transactions API"
  title: "Balance Watch: Transactions API"
  version: "1.0.0"
basePath: "/watch"

paths:
  /transactions/{id}:
    delete:
      tags:
        - "transactions"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Success"
        404:
          description: "Cannot find transaction"
    put:
      tags:
        - "transactions"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: integer
          format: int64
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        405:
          description: "Invalid Input"
        200:
          description: "Successful transaction update"
          headers:
            X-Last-Modified:
              description: An epoch tag that represents the last modification
              type: integer
              format: int64
    get:
      tags:
        - "transactions"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Transaction"
  /xtransactions:
    get:
      tags:
        - "transactions"
      produces:
        - "application/json"
      parameters:
        - name: "year"
          in: "query"
          required: true
          type: "integer"
          format: "int32"
        - name: "month"
          in: "query"
          required: true
          type: "integer"
          minimum: 1
          maximum: 12
        - name: "ttId"
          in: "query"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionWrapper"
        400:
          description: "Invalid request supplied"
  /transactions:
    get:
      tags:
        - "transactions"
      produces:
        - "application/json"
      parameters:
        - name: "year"
          in: "query"
          required: true
          type: "integer"
          format: "int32"
        - name: "month"
          in: "query"
          required: true
          type: "integer"
          minimum: 1
          maximum: 12
        - name: "account"
          in: "query"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TransactionWrapper"
        400:
          description: "Invalid year/month/account supplied"
        404:
          description: "No transactions found"
    post:
      tags:
        - "transactions"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        201:
          description: "Success"
          headers:
            X-Internal-Id:
              type: "integer"
              format: "int64"
              description: "Internal ID used by the database"
        405:
          description: "Invalid input"

definitions:
  TransactionWrapper:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Internal ID used by the database"
      data:
        $ref: "#/definitions/Transaction"
  Transaction:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date-time"
      type:
        type: "string"
      amount:
        type: "number"
        format: "currency"
      way:
        enum:
          - DEBIT
          - CREDIT
      note:
        type: "string"
      noteXtra:
        type: "string"
      account:
        type: integer
        format: int64
      accountConnection:
        type: integer
        format: int64
      ttIdGen:
        type: "integer"
        format: "int64"
      flagSubmitted:
        type: "boolean"