swagger: "2.0"
info:
  description: "User Account API"
  title: "Balance Watch: Users and Accounts API"
  version: "1.0.0"
basePath: "/watch"

paths:
  /users/{userId}/accounts:
    get:
      tags:
        - "accounts"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AccountWrapper"
        404:
          description: "No accounts found for specified user"
    post:
      tags:
        - "accounts"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          type: integer
          format: int64
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Account"
      responses:
        201:
          description: "Success"
          headers:
            X-Internal-Id:
              type: "integer"
              format: "int64"
              description: "Internal ID used by the database"
        405:
          description: "Invalid input"

  /accounts/{accountId}:
    put:
      tags:
        - "accounts"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: accountId
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Account"
      responses:
        405:
          description: "Invalid input"
  /users/{userId}:
    get:
      tags:
        - "users"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/UserWrapper"
        404:
          description: "No user found with specified id"
    put:
      tags:
        - "users"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          type: integer
          format: int64
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        405:
          description: "Invalid input"
  /users:
    post:
      tags:
        - "users"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "Success"
          headers:
            X-Internal-Id:
              type: "integer"
              format: "int64"
              description: "Internal ID used by the database"
        405:
          description: "Invalid input"
definitions:
  UserWrapper:
    type: object
    properties:
      id:
        type: integer
        format: int64
      data:
        $ref: '#/definitions/User'
  User:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
        format: email
  AccountWrapper:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: "Internal ID used by the database"
      data:
        $ref: '#/definitions/Account'
  Account:
    type: object
    properties:
      accountNumber:
        type: string
      desc:
        type: string